
---

- name: Create a started container
  lxd_container:
    name: "{{ lxdhost }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ubuntu/xenial/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600


- name: apt update   
  delegate_to: "{{ host }}"   
  raw: apt update


- name: install nginx
  delegate_to: "{{ host }}"
  raw: apt install nginx -y

- name: install git
  delegate_to: "{{ host }}"
  raw: apt install git -y

- name: copy files
  delegate_to: "{{ host }}"
  raw: git clone https://github.com/BlackrockDigital/startbootstrap-landing-page.git

- name: move files
  delegate_to: "{{ host }}"
  raw: cp -r startbootstrap-landing-page/. /usr/share/nginx/html
